<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="kentico.xperience.admin" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.azurestorage" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.cloud" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.imageprocessing" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.managementapi" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.mjml" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.webapp" Version="31.9.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.35.0.4138" />
    <PackageVersion Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
  </ItemGroup>
</Project>